
export const colorOptions = [
  { value: "berry_red", label: "Berry Red", color: "#D50032" },
  { value: "red", label: "Red", color: "#FF0000" },
  { value: "orange", label: "Orange", color: "#FF6600" },
  { value: "yellow", label: "Yellow", color: "#FFEB3B" },
  { value: "olive_green", label: "Olive Green", color: "#808000" },
  { value: "lime_green", label: "Lime Green", color: "#00FF00" },
  { value: "green", label: "Green", color: "#008000" },
  { value: "mint_green", label: "Mint Green", color: "#98FF98" },
  { value: "teal", label: "Teal", color: "#008080" },
  { value: "sky_blue", label: "Sky Blue", color: "#87CEEB" },
  { value: "light_blue", label: "Light Blue", color: "#ADD8E6" },
  { value: "blue", label: "Blue", color: "#0000FF" },
  { value: "grape", label: "Grape", color: "#6F2DA8" },
  { value: "violet", label: "Violet", color: "#8A2BE2" },
  { value: "lavender", label: "Lavender", color: "#E6E6FA" },
  { value: "magenta", label: "Magenta", color: "#FF00FF" },
  { value: "salmon", label: "Salmon", color: "#FA8072" },
  { value: "charcoal", label: "Charcoal", color: "#36454F" },
  { value: "grey", label: "Grey", color: "#808080" },
  { value: "taupe", label: "Taupe", color: "#483C32" },
];
